language: cpp

os:
    - linux
    - osx

compiler:
    - gcc
    - clang

notifications:
    email:
        on_failure: always
        on_success: change

sudo: false

matrix:
    exclude:
        - os: osx
          compiler: gcc

addons:
    apt:
        packages:
            - cmake

before_install:
    - export PATH=$HOME/.local/bin:$PATH
    - pip install cpp-coveralls --user `whoami`

before_script:
    - cd $TRAVIS_BUILD_DIR
    - mkdir build
    - cd build
    - cmake .. -DCMAKE_BUILD_TYPE=coverage
    - make VERBOSE=1

script:
    - ctest -V

after_success:
    # as described at: https://github.com/eddyxu/cpp-coveralls
    - coveralls -E '.*test.*' -E '.*vendor.*' -E '/usr.*' -E '.*CMake.*' --gcov-options '\-lp' -r .. 
