common:
  memory: 64g
  cpucores: 12
varscan:
  minBaseQual: 28
  minVAF: 0.10
  somatic:
    minCoverage: 8
    tumorPurity: 0.5
    minFreqForHom: "0.75"
  fpfilter:
    minVarCount: 4
annovar:
  protocol: 'refGene,gnomad_exome,exac03,esp6500siv2_ea,EUR.sites.2015_08,avsnp150,clinvar_20180603,intervar_20180118,dbnsfp35a,cosmic86_coding,cosmic86_noncoding'
  argop: 'g,f,f,f,f,f,f,f,f,f,f'
reference:
  genome: hg19.fa
  length: hg19_chr.len
  dbSNP: snp150hg19.vcf.gz
  mappability: out100m2_hg19.gem
  sequencing:
    capture_regions: CaptureRegions.bed
