FROM miracum_pipe_base:latest

ENV HTTP_PROXY "http://proxy.ibsm.uni-freiburg.de:8080"
ENV HTTPS_PROXY "http://proxy.ibsm.uni-freiburg.de:8080"

ADD . /opt/MIRACUM-Pipe

RUN Rscript /opt/MIRACUM-Pipe/RScripts/install_packages.R