FROM miracum_pipe_base:latest

ENV http_proxy http://proxy.ibsm.uni-freiburg.de:8080
ENV https_proxy http://proxy.ibsm.uni-freiburg.de:8080

ADD . /opt/MIRACUM-Pipe

RUN Rscript /opt/MIRACUM-Pipe/RScripts/install_packages.R