FROM miracumpipe_tools:latest

COPY ./*.sh /opt/MIRACUM-Pipe/
COPY ./RScripts/* /opt/MIRACUM-Pipe/RScripts/
COPY ./conf/default.yaml /opt/MIRACUM-Pipe/conf/default.yaml

# define volumes
VOLUME /opt/MIRACUM-Pipe/assets/input
VOLUME /opt/MIRACUM-Pipe/assets/output
VOLUME /opt/MIRACUM-Pipe/assets/references

VOLUME /opt/MIRACUM-Pipe/tools/annovar
VOLUME /opt/MIRACUM-Pipe/tools/gatk

VOLUME /opt/MIRACUM-Pipe/conf