FROM miracum_pipe_r:latest

ENV http_proxy http://proxy.ibsm.uni-freiburg.de:8080
ENV https_proxy http://proxy.ibsm.uni-freiburg.de:8080

ADD . /opt/MIRACUM-Pipe

RUN /opt/MIRACUM-Pipe/tools/install.sh
