\documentclass[woside,a4paper,12pt]{article}
\usepackage{mathptmx, helvet, courier}
\renewcommand\familydefault{\sfdefault}
\usepackage[german]{babel}
\usepackage[utf8]{inputenc}
\usepackage[T1]{fontenc}
\usepackage{float}
\usepackage{graphicx}
\usepackage{caption}
\usepackage{geometry}
\geometry{verbose,tmargin=2.5cm,bmargin=2.5cm,lmargin=2.5cm,rmargin=2.5cm}
\setcounter{secnumdepth}{2}
\setcounter{tocdepth}{2}
\usepackage{url}
\usepackage[unicode=true,pdfusetitle,
 bookmarks=true,bookmarksnumbered=true,bookmarksopen=true,bookmarksopenlevel=2,
 breaklinks=false,pdfborder={0 0 1},backref=false,colorlinks=false]
 {hyperref}
\hypersetup{pdfstartview={XYZ null null 1}}
\usepackage{breakurl}
\usepackage{booktabs}
\usepackage{longtable}
\usepackage{array}
\usepackage{multirow}
\usepackage[table]{xcolor}
\usepackage{wrapfig}
\usepackage{float}
\usepackage{colortbl}
\usepackage{pdflscape}
\usepackage{tabu}
\usepackage{threeparttable}
\usepackage{fullpage}
\usepackage{pdflscape}
\usepackage{ifthen}
\usepackage{subfig}
\usepackage{acronym}

\begin{document}

<<setup, include=FALSE, cache=FALSE, echo=FALSE, eval=TRUE>>=
library(knitr)
library(kableExtra)
options(knitr.table.format = "latex")
# set global chunk options
opts_chunk$set(fig.align = "center", fig.show = "hold")
options(formatR.arrow = TRUE, width = 90)

sample <- paste(unlist(strsplit(sample, split = "_")), collapse = " ")
@

\title{\Sexpr{sample} - Report}

\author{\Sexpr{author}}

\maketitle

\section*{Analyse-Ergebnisse auf einen Blick}

<<eval=TRUE, results="tex", echo=FALSE>>=
tmp1 <- key_results

kable(tmp1, booktabs = T, row.names = F, caption = "\\footnotesize{Schl\"usselergebnisse der Analyse}") %>% kable_styling(latex_options = c( "hold_position"), font_size = 9) %>% column_spec(1, width = "16em") %>% column_spec(c(2:3), width = "12em") %>% column_spec(4, width = "5em")
@

\ifx{\Sexpr{length(which(mutation_analysis_result_mutect2$som_mut_tab$is_oncogene == 1 | mutation_analysis_result_mutect2$som_mut_tab$is_tumorsuppressor == 1 | mutation_analysis_result_mutect2$som_mut_tab$InterVar_automated %in% c("Pathogenic", "Likely pathogenic") | mutation_analysis_result_mutect2$som_mut_tab$CLNSIG %in% c("Pathogenic", "Likely_pathogenic", "Conflicting_interpretations_of_pathogenicity")))}}0
{\textbf{Keine Mutationen in Cancergenen und keine Mutationen mit hoher ACMG-Klassifikation identifiziert.}}
\else
{
<<highlight, echo=FALSE, eval=TRUE, results="tex", warning=FALSE>>=
tmp <- highlight_table$highlight
if(dim(tmp)[1] != 0) {
  cap <- "\\footnotesize{Mutationen mit ACMG Klassifizierungen: Warscheinlich Pathogen (4), Pathogen (5), Conflicting Interpretations of Pathogenicity (4*). Revel: \\textbf{D}(eleterious), \\textbf{N}(eutral). Hotspots sind \\textbf{fett} dargestellt.}"
  if(length(highlight_table$id_hs) > 0) {
    kable(tmp, format = "latex", caption = cap, booktabs = T, longtable = T, digits = 2, row.names = F, escape = FALSE) %>% kable_styling(latex_options = c( "HOLD_position", "repeat_header"), font_size = 9) %>% row_spec(highlight_table$id_hs, bold = TRUE) %>% column_spec(1, bold = T) %>% row_spec(0, angle = 60)
  } else {
    kable(tmp, format = "latex", caption = cap, booktabs = T, longtable = T, digits = 2, row.names = F, escape = FALSE) %>% kable_styling(latex_options = c( "HOLD_position", "repeat_header"), font_size = 9) %>% column_spec(1, bold = T) %>% row_spec(0, angle = 60)
  }
} else {
  cat("Keine Cancergenes und keine Mutationen mit hoher ACMG Einsch\"atzung identifiziert.")
}

@
}
\fi

<<eval=TRUE, results="tex", echo=FALSE>>=
kable(sq_tab, booktabs = T, row.names = F, caption = "\\footnotesize{Auff{\"a}lligkeiten in Qualit{\"a}tsmerkmalen der Proben}") %>% kable_styling(latex_options = c( "hold_position"), font_size = 9)
@

\clearpage

\tableofcontents

\clearpage

%%%% Mutationsanalyse %%%%
\section{Mutationsanalyse}
\subsection{Detaillierte \"Ubersicht}
In der Analyse werden nur seltene Mutationen mit einer \ac{VAF} über \Sexpr{vaf}\% betrachtet. Gezeigt werden Mutationen vom Typ \acp{SNV}, \acp{DNV} und \acp{InDels}. Letztere sind Mutationen, die in der Keimbahn heterozygot vorliegen, im Tumor allerdings homozygot.\\
Im Weiteren werden die Ergebnisse der Mutationsanalyse in Tabellen dargestellt. Zunächst eine Übersicht über die Anzahl der Mutationen, aufgeteilt in verschiedene Mutationstypen (Tab \ref{mut_ana_ov}). Es wird gelistet, wie viele dieser Mutationen als ein sogenanntes Cancergene nach OncoKB, aufgeteilt in \ac{TSG} und \ac{OG}, identifiziert wurden. Desweitern wird die Anzahl der sogenannten \ac{HS} nach cancerhotspots.org angegeben.\\
Die Lage der Mutationen im Genom wird, aufgeteilt nach Mutationstyp (SNV und InDels), im Circosplot dargestellt (Abb \ref{cir_plot}). Die gelben Bereiche sind die Regionen, die das Panel abdeckt. Wenn Fusionen in der Probe identifiziert wurden, werden diese im inneren Kreis abgebildet.

<<mut_ana_ov, eval=TRUE, results="tex", echo=FALSE>>=
kable(som_muts, booktabs = T, row.names = F, caption = paste("Zusammenfassung der identifizierten Mutationen mit VAF > ",vaf,"\\% \\label{mut_ana_ov}")) %>% kable_styling(latex_options = c( "hold_position"), font_size = 9)
@

\begin{figure}[H]
\centering
\includegraphics[width=0.53\textwidth]{\Sexpr{outfile_circos_mutect2}}
\caption{Circos Plot mit allen Mutationen \"uber VAF \Sexpr{vaf}.}
\label{cir_plot}
\end{figure}
\clearpage

\subsection{Cancer Genes}
\subsubsection{Mutationen}\label{som_mut_section}
\definecolor{aquamarine}{rgb}{0, 1.0, 1.0}

In der folgenden Tabellen werden Gensymbol und der entsprechende Aminos\"aurenaustausch gelistet.
Die Funktion der Mutationen werden durch Abk\"urzungen beschrieben, welche im Ahang aufgef\"uhrt sind.
Die \ac{VAF} wird gelistet, zusammen mit den zu Grunde liegenden Readcounts. Zun\"achst die Anzahl an Variantenreads, danach die Gesamtcoverage an dieser Stelle.
Außerdem werden nur seltene Mutationen gelistet. Selten bedeutet dabei, dass die \ac{MAF} unter \Sexpr{maf_cutoff} (\Sexpr{maf_cutoff*100}\%) liegen muss, basierend auf der Datenbank gnomAD exome.
Desweiteren wurden Strukturanalysen via REVEL zu den entsprechend mutierten Proteinen durchgef\"uhrt.

Die Varianten werden nach den ACMG Kriterien basierend auf den Datenbanken \ac{InterVar} und \ac{ClinVar} klassifiziert, siehe Anhang \ref{ACMG_class}. \acp{InDels} und \acp{DNV} werden dabei allerdings nicht ber\"ucksichtigt. Wird bei ClinVar die Klasse \textit{Conflicting Interpretations of Pathogenicity} berichtet, werden die Varianten in die Klasse \textbf{4*} eingeteilt.

Der Wertebereich von REVEL liegt im Intervall [0,1], wobei die H\"ohe des Wertes die Pathogenit\"at der Mutation angibt, d.h. 1 entspricht der h\"ochsten Pathogenit\"at. Alle Varianten mit einem REVEL Wert >0.5 tragen zus\"atzlich den Buchstaben \ac{REVEL-D} andernfalls ein \ac{REVEL-N}. \textbf{Generell gilt eine Mutation mit einem REVEL Wert > 0.5 als deletär.}

Die Analyse beinhaltet zus\"atzliche Annotationen bekannter Mutationen wie Cosmic, Clinvar und dbSNP. Die Ergebnisse werden nur reduziert und \"ubersichtlich dargestellt. Es werden f\"ur die Mutationen hier nur die entsprechenden Cosmic Nummern angegeben.
Am Ende wird die Zuordnung des Gens als Cancergene nach der Klassifikation von OncoKB dargestellt. \textbf{Mutationen in einem \ac{HS}} sind fett markiert. Die folgende Tabelle \ref{som_mut_cg} enth\"alt alle \acp{SNV}, \acp{DNV} und \acp{InDel} in Cancergenen f\"ur diese Probe.

Bei den \textbf{Gensymbolen} ist ein Link zu \textbf{\textit{Genome Nexus}} hinterlegt. Dort wird ein Lollipop-Plot zur Lage der Mutation im Gen angezeigt sowie weitere Informationen. Beim \textbf{Aminosäurenaustausch} ist ein Link zum Eintrag der Mutation in der \textbf{\ac{VICC}} verkn\"upft. Bei der \textbf{Funktion} ist ein Link zu \textbf{\ac{VarSome}} hinterlegt. Dort sind auch \acp{InDel} und \acp{DNV} nach ACMG klassifiziert. Diese Links funktionieren allerdings aufgrund eines Sonderzeichens in der URL nicht bei Verwendung des Dokuments mit der Vorschau von Apple.

Im Anhang befinden sich Tabellen zu allen detektierten Mutationen (Kap \ref{all_som_mut}). Es werden allerdings nur seltene, exonische Mutationen mit einer VAF über \Sexpr{vaf}\% gelistet.

<<som_mut_cg, eval=TRUE, results="tex", echo=FALSE>>=
if (is.null(sum_mut_cg$muts_tab)) {
#if(dim(sum_mut_cg$muts_tab)[1] == 0) {
  kable(data.frame('Gen' = c("."), 'AA-Austausch' = c("."), 'Funktion' = c("."), 'VAF' = c("."), 'MAF' = c("."), 'Condel' = c("."), 'Cosmic' = c("."), 'OG' = c("."), 'TSG' = c(".")), format = "latex", caption = "Es wurden keine somatischen Mutationen in Cancergenes identifiziert.\\label{som_mut_cg}", booktabs = T, longtable = T, digits = 2, row.names = F) %>% kable_styling(latex_options = c( "HOLD_position"), font_size = 9) %>% column_spec(c(2, 7), width = "6em") %>% column_spec(c(1, 5), width = "4em") %>% column_spec(c(3:4), width = "4em") %>% column_spec(c(6, 8:9), width = "2em") %>% row_spec(0, angle = 60)
} else {
  cap_1 <- "Alle identifizierten Mutationen in Cancergenes geordnet nach VAF.\\label{som_mut_cg}."
  if (length(sum_mut_cg$id_hs) > 0) {
    kable(sum_mut_cg$muts_tab, format = "latex", caption = cap_1, booktabs = T, longtable = T, digits = 2, row.names = F, escape = FALSE) %>% kable_styling(latex_options = c( "HOLD_position", "repeat_header"), font_size = 9) %>% column_spec(c(2, 8), width = "6em") %>% column_spec(c(1, 5), width = "4em") %>% column_spec(c(3:4), width = "4em") %>% column_spec(c(6, 9), width = "2em") %>% row_spec(0, angle = 60) %>% row_spec(sum_mut_cg$id_hs, bold = TRUE)
  } else {
      kable(sum_mut_cg$muts_tab, format = "latex", caption = cap_1, booktabs = T, longtable = T, digits = 2, row.names = F, escape = FALSE) %>% kable_styling(latex_options = c( "HOLD_position", "repeat_header"), font_size = 9) %>% column_spec(c(2, 8), width = "6em") %>% column_spec(c(1, 5), width = "4em") %>% column_spec(c(3:4), width = "4em") %>% column_spec(c(6, 9), width = "2em") %>% row_spec(0, angle = 60)
  }
}
n_cnv <- round(x = dim(cnv_analysis_results$cnvs_annotated$CNVsAnnotated)[1], digits = 0)
@
\clearpage

%%%% MUTATIONSANALYSE %%%%
\section{Copy Number Variations}
\subsection{\"Ubersicht}
Im folgenden sind die \Sexpr{n_cnv} signifikanten Regionen mit \acp{CNV} als Ideogramm dargestellt (Abb \ref{ideogram}). Dabei wird über allen Chromosomen in den Zeilen die totale Anzahl an Kopien farbig markiert aufgetragen. Dabei wird  auf das Markieren von Regionen mit normaler Ploidität verzichtet. In blau dargestellt sind Verluste, je dunkler das Blau, desto weniger Kopien gibt es von dieser Region (1 oder 0). Regionen mit gesteigerten Kopien sind rot markiert, je dunkler das Rot, desto mehr Kopien gibt es in der Region (3 aufsteigend).

\begin{figure}[H]
\centering
\includegraphics[width=\textwidth]{\Sexpr{cnv_ideogram_plot}}
\caption{\acp{CNV} - Ideogramm}
\label{ideogram}
\end{figure}
\clearpage

\subsection{CNVs}
Wie bei den Mutationen werden auch bei den CNVs betroffene Cancergenen (Onkogene und Tumorsuppressoren) genauer betrachtet und in folgenden Tabellen dargestellt. Dabei werden für Gene in Tabelle \ref{cnv_og} Losse und Gains von Kopien dargestellt.

<<eval=TRUE, results="tex", echo=FALSE, warning = FALSE>>=
kables(
  list(
    kable(
      cnvs_og$Gains, format = "latex", booktabs = T, valign = 't', row.names = F) %>% row_spec(0, angle = 60)
  ,
  kable(cnvs_og$Losses, format = "latex", booktabs = T, valign = 't', row.names = F) %>% row_spec(0, angle = 60)
  ,
  kable(
    cnvs_og$Different, format = "latex", booktabs = T, valign = 't', row.names = F) %>% row_spec(0, angle = 60)
  ),
  caption = "Identifizierte \\acp{CNV} in Onkogenen\\label{cnv_og}"
) %>% kable_styling(latex_options = c("HOLD_position"), font_size = 8)
@

<<eval=FALSE, results="tex", echo=FALSE>>=
tmpg <- tmp[-idl, c(1:2, 4)]
tmpg$Oncogene <- gsub(pattern = ",", replacement = ", ", x = tmpg$Oncogene)
colnames(tmpg) <- colnames(tmpo)
if(dim(tmpg)[1]!=0){
  kable(tmpg, format = "latex", caption = "Identifizierte Gains in Onkogenen\\label{og_gain}", booktabs = T, longtable = T, digits = 2, row.names = F) %>% kable_styling(latex_options = c( "HOLD_position", "repeat_header"), font_size = 9) %>% column_spec(c(3), width = "30em") %>% column_spec(c(1:2), width = "1em") %>% row_spec(0, angle = 60)
}else {
  cap <- "Keine Gains in Onkogenen identifiziert.\\label{og_gain}"
  kable(data.frame('Chromosom' = c("."), 'Kopien' = c("."), 'Onkogene' = c(".")), format = "latex", caption = cap, booktabs = T, longtable = T, digits = 2, row.names = F) %>% kable_styling(latex_options = c( "HOLD_position", "repeat_header"), font_size = 9) %>% column_spec(c(3), width = "30em") %>% column_spec(c(1:2), width = "1em") %>% row_spec(0, angle = 60)
  }
@

<<eval=TRUE, results="tex", echo=FALSE, warning = FALSE>>=
kables(
  list(
    kable(
      cnvs_tsg$Gains, format = "latex", booktabs = T, valign = 't', row.names = F) %>% row_spec(0, angle = 60)
  ,
  kable(cnvs_tsg$Losses, format = "latex", booktabs = T, valign = 't', row.names = F) %>% row_spec(0, angle = 60)
  ,
  kable(
    cnvs_tsg$Different, format = "latex", booktabs = T, valign = 't', row.names = F) %>% row_spec(0, angle = 60)
  ),
  caption = "Identifizierte \\acp{CNV} in Tumorsuppressoren\\label{cnv_tsg}"
) %>% kable_styling(latex_options = c("HOLD_position"), font_size = 8)
@

<<eval=FALSE, results="tex", echo=FALSE>>=
tmp <- cnv_analysis_results$cnvs_annotated$CNVTumorSuppressors
idl <- which(tmp$status == "loss")
tmpo <- tmp[idl, c(1:2, 4)]
tmpo$TumorSuppressor <- gsub(pattern = ",", replacement = ", ", x = tmpo$TumorSuppressor)
colnames(tmpo) <- c("Chromosom", "Kopien", "Tumorsuppressor")
if(dim(tmpo)[1]!=0){
  kable(tmpo, format = "latex", caption = "Identifizierte Losse in Tumorsuppressoren\\label{tsg_loss}", booktabs = T, longtable = T, digits = 2, row.names = F) %>% kable_styling(latex_options = c( "HOLD_position", "repeat_header"), font_size = 9) %>% column_spec(c(3), width = "30em") %>% column_spec(c(1:2), width = "2em") %>% row_spec(0, angle = 60)
}else {
  cap <- "Keine Losse in Tumorsuppressoren identifiziert.\\label{tsg_loss}"
  kable(data.frame('Chromosom' = c("."), 'Kopien' = c("."), 'Onkogene' = c(".")), format = "latex", caption = cap, booktabs = T, longtable = T, digits = 2, row.names = F) %>% kable_styling(latex_options = c( "HOLD_position", "repeat_header"), font_size = 9) %>% column_spec(c(3), width = "30em") %>% column_spec(c(1:2), width = "1em") %>% row_spec(0, angle = 60)
  }
@

\clearpage
\section{Wichtige Signalwege}\label{imp_pathways_section}
Es werden fünf wichtige Signalwege betrachtet: \ac{RAF-MEK-ERK}, \ac{PI3K-AKT-mTOR}, \ac{DamResp}, \ac{CellCycle} und \ac{TyrKin}. Es wird untersucht, welche Gene in diesen Signalwege eine Mutation tragen. Diese Mutationen sind analog zu Kapitel \ref{som_mut_section} in Tabelle \ref{imp_ptws} dargestellt. Wenn in einem Signalweg keine Mutation identifiziert wurde, taucht er in der Tabelle nicht auf.\\
Außerdem werden auch die CNVs auf ihre Zugehörigkeit zu den fünf wichtigen Signalwegen untersucht und in Tabelle \ref{imp_ptws_cnv} dargestellt. Dabei werden Gene mit der gleichen totalen Kopienanzahl in einer Zeile zusammengefasst.

\subsection{Mutationen in wichtigen Signalwegen}
<<som_mut_imp_pws, echo=FALSE, eval=TRUE, results="tex">>=
options(knitr.kable.NA = ".")
tmp <- som_mut_pthw
if (is.null(tmp)) {
#if (dim(tmp)[1] == 0){
  cap <- "Keine Mutationen in wichtigen Signalwegen identifiziert.\\label{imp_ptws}"
  kable(data.frame(Signalweg = c("."), Gen = c("."), 'AA-Austausch' = c("."), Funktion = c("."), VAF = c("."), MAF = c("."), Condel = c("."), Cosmic = c(".")), format = "latex", caption = cap, booktabs = T, longtable = T, row.names = F, escape = FALSE) %>% kable_styling(latex_options = c( "HOLD_position", "repeat_header"), font_size = 9) %>% column_spec(c(2:3, 8), width = "5em") %>% column_spec(c(4:6), width = "3em") %>% column_spec(c(7), width = "2em") %>% column_spec(1, bold = T) %>% row_spec(0, angle = 60)
} else {
  kable(tmp, format = "latex", caption = "Identifizierte somatische Mutationen in wichtigen Signalwegen\\label{imp_ptws}", booktabs = T, longtable = T, row.names = F, escape = F) %>% kable_styling(latex_options = c( "HOLD_position", "repeat_header"), font_size = 9) %>% column_spec(c(3, 4, 9), width = "5em") %>% column_spec(c(1:2, 5:6, 7), width = "3em") %>% column_spec(c(8), width = "1em") %>% column_spec(1, bold = T) %>% row_spec(0, angle = 60)
}
@
\clearpage
\subsection{CNVs in wichtigen Signalwegen}
<<echo=FALSE, eval=TRUE, results="tex">>=
tmp <- cnvs_pthws
if (is.null(tmp)) {
#if (dim(tmp)[1] == 0){
  cap <- "Es wurden keine CNVs in wichtigen Signalwegen identifiziert."
  kable(data.frame(Signalweg = c("."), Status = c("."), Kopien = c("."), Gene = c(".")), format = "latex", caption = cap, booktabs = T, longtable = T, row.names = F, escape = FALSE) %>% kable_styling(latex_options = c("HOLD_position", "repeat_header"), font_size = 9, full_width = T) %>% column_spec(1, width = "15em") %>% column_spec(c(2:3), width = "5em") %>% column_spec(1, bold = T) %>% row_spec(0, angle = 60)
} else {
  kable(tmp, format = "latex", caption = " Identifizierte CNVs in wichtigen Signalwegen\\label{imp_ptws_cnv}", booktabs = T, longtable = T, row.names = F) %>% kable_styling(latex_options = c("HOLD_position", "repeat_header"), font_size = 9, full_width = F) %>% column_spec(1, width = "15em") %>% column_spec(c(2:3), width = "5em") %>% column_spec(4, width = "30em") %>% column_spec(1, bold = T) %>% row_spec(0, angle = 60)
}
@ 

\clearpage
\section{Weitere Analysen}
\subsection{Mutationssignaturen}
Untersucht werden die Mutationssignaturen basierend auf den COSMIC Mutation Signatures (V1) für alle Mutationen in der Probe. In der folgenden Tabelle \ref{mut_sig} werden nur Signaturen gelistet, die einen Anteil größer als 1\% haben. Die Signatur AC3 wird als \textit{BRCAness} bezeichnet.\\
Der TopArt-Score besteht aus vier verschiedenen Anteilen. Die ersten beiden Kategorien P1 und P2 sind phänotypische Kriterien. Für den TopArt-Score P1 ist wichtig, ob die \textit{BRCAness}-Signatur vorhanden ist. Ist sie nicht vorhanden, bekommt der Patient in dieser Kategorie null Punkte. Ist die Signatur vorhanden, das KI enthält aber die Null, erhält der Patietn einen Punkt. Enthält das KI die null nicht, so gibt es zwei Punkte. Das zweite phänotypische Kriterium P2 können wir nicht auswerten.

<<mut_sig, echo=FALSE, eval=TRUE, results='tex'>>=
tmp <- mut_sig
tmp <- tmp[, c(1:3)]
tmp[,3] <- tmp[,3]*100
colnames(tmp) <- c("Signatur", "Beschreibung", "Anteil in %")
kable(tmp, caption = "Ergebnisse Mutationssignatur Analyse\\label{mut_sig}", booktabs = T, row.names = F, digits = 2) %>% kable_styling(latex_options = c("striped", "HOLD_position"), font_size = 9, full_width = T)
@

\subsection{TopArt Gene für G1}

Die beiden anderen Kategorien G1 und G2 für den TopArt-Score sind genotypische Kriterien. Für die erste Kategorie werden die Gene mit Mutationen auf ihre Zugehörigkeit zu einer Liste aus 181 Genen geprüft. Wenn solche Mutationen detektiert werden, so sind sie in folgender Tabelle dargestellt (Tab \ref{top_art}). Gibt es in einem Gen eine homozygote Mutation, erhält der Patient in dieser Kategorie zwei Punkte. Gibt es eine heterozygote, so erhält er einen Punkt. Die zweite genotypische Kategorie G2 betrachtet Keimbahn-Mutationen. Diese können wir im Moment nicht auswerten.\\
Hat der Patient insgesamt mehr als 3 Punkte und stammt mindestens einer dieser Punkte aus den genotypischen Kriterien, so ist der TopArt-Score positiv.

<<top_art, echo=FALSE, eval=TRUE, results="tex">>=
options(knitr.kable.NA = ".")
tmp <- som_mut_topart
if (is.null(tmp)) {
#if(dim(som_mut_topart)[1] == 0) {
  kable(data.frame('Signalweg' = c("."), 'Gen' = c("."), 'AA-Austausch' = c("."), 'Funktion' = c("."), 'VAF (Coverage)' = c("."), 'MAF' = c("."), 'Condel' = c("."), 'Cosmic' = c(".")), format = "latex", caption = "Keine somatischen Mutationen in TOPART-G1-Genen.\\label{top_art}", booktabs = T, longtable = T, row.names = F) %>% kable_styling(latex_options = c( "HOLD_position", "repeat_header"), font_size = 9) %>% column_spec(c(2:3, 8), width = "5em") %>% column_spec(c(4:6), width = "3em") %>% column_spec(c(7), width = "2em") %>% column_spec(1, bold = T) %>% row_spec(0, angle = 60)
} else{
  kable(tmp, format = "latex", caption = "Mutationen in TOPART-G1-Genen\\label{top_art}.", booktabs = T, longtable = T, row.names = F, escape = F) %>% kable_styling(latex_options = c( "HOLD_position", "repeat_header"), font_size = 9) %>% column_spec(c(1:3, 4, 9), width = "5em") %>% column_spec(c(2:3, 8), width = "3em") %>% column_spec(c(7), width = "2em") %>% column_spec(1, bold = T) %>% row_spec(0, angle = 60)
  }
@
\clearpage

%%%% QUALITÄT %%%%
\section{Qualit\"{a}tskontrollen und Sequenzierungsstatistiken}

Für die Analysen werden nur Reads mit einer durchschnittlichen Basenqualität von mehr als 28 nach der \ac{BQSR} berücksichtigt. In Abbildung \ref{base_qual} sind die Basenqualitäten für jede Position in den Reads dargestellt. Für jede Probe einmal direkt aus dem Sequenzierer (Abb \ref{base_qual}, obere Reihe) und einmal nach der BQSR (Abb \ref{base_qual}, untere Reihe).

\begin{figure}[h]
\centering
\subfloat[Tumor Qualit\"at]{\includegraphics[width = 0.4\textwidth]{\Sexpr{tumor}}} \quad %
\subfloat[Tumor Qualit\"at nach BQSR]{\includegraphics[width = 0.4\textwidth]{\Sexpr{tumor_bsqr}}} \quad %
\caption{Darstellung der Sequenzierung als Output aus dem Sequenzierer, (a), und nach der \ac{BQSR}, (b)}
\label{base_qual}
\end{figure}
\clearpage

<<eval=TRUE, results="tex", echo=FALSE, warning=FALSE>>=
df <- data.frame(
  Kriterium = c('Librarygr\"o\"se', "Mean Coverage", "Basen > 8 Reads", "Basen > 40 Reads", "Exonische Basen > 8 Reads", "Exonische Basen > 40 Reads", 'Insertgr\"o\"se (Standardabweichung)', "QC-Anteil", 'Mean Qualit\"at pro Base'),
  Tumor = c(
    paste0(stats$avreads$nRT, " Mio Reads"),
    paste0(round(x = sum(stats$cover$cov[[1]][, 2] * stats$cover$cov[[1]][, 5]), digits = 2), " X"),
    paste0(round(stats$cover$perc[[1]][1], digits = 2) * 100, "%"),
    paste0(round(stats$cover$perc[[1]][2], digits = 2) * 100, "%"),
    paste0(round(stats$cover_exons$perc[[1]][1], digits = 2) * 100, "%"),
    paste0(round(stats$cover_exons$perc[[1]][2], digits = 2) * 100, "%"),
    paste0(stats$avreads$tin, "bp (", stats$avreads$tin_sd, ")"),
    paste0(stats$qc_check$gc_content[[1]], "%"),
    paste0(round(stats$qc_check$mean_QC[[1]], digits = 2))
  ),
  Mindestwert = c("100 Mio Reads", "80 X", "90%", "90%", "90%", "90%", "100bp", "40-60%", 28)
)

kable(df, format = "latex", caption = "Qualit\"atskriterien\\label{qual}", booktabs = T, row.names = F) %>% kable_styling(latex_options = c( "HOLD_position"), font_size = 9)

@

\subsection{Coverage}

Die Mean-Coverage und die Gesamtcoverage der Proben ist ein weiteres Qualitätsmerkmal. Sind die Werte zu niedrig, sind viele Stellen im Genom unzureichend abgedeckt. Abbildung \ref{cov_plot} zeigt die kummulative Verteilung, durch die der Anteil an targeted Basen, die von einer bestimmten Anzahl an Reads abgedeckt sind, beschrieben wird.

\begin{figure}[h]
\centering
\includegraphics[width=0.6\textwidth]{\Sexpr{coverage_out}}
\caption{Coverage}
\label{cov_plot}
\end{figure}
\clearpage


% Anhang
\appendix
\section{Tabellen aller detektierten Mutationen}
\subsection{Mutationen}\label{all_som_mut}
<<eval=TRUE, results="tex", echo=FALSE>>=
if(is.null(som_all$muts_tab) || dim(som_all$muts_tab)[1] == 0) {
  kable(data.frame('Gen' = c("."), 'AA-Austausch' = c("."), 'Funktion' = c("."), 'VAF' = c("."), 'MAF' = c("."), 'Condel' = c("."), 'Cosmic' = c("."), 'OG' = c("."), 'TSG' = c(".")), format = "latex", caption = "Es wurden keine somatischen Mutationen identifiziert.", booktabs = T, longtable = T, digits = 2, row.names = F) %>% kable_styling(latex_options = c( "HOLD_position"), font_size = 9) %>% column_spec(c(2, 7), width = "6em") %>% column_spec(c(1, 5), width = "4em") %>% column_spec(c(3:4), width = "4em") %>% column_spec(c(6, 8:9), width = "2em") %>% row_spec(0, angle = 60)
} else {
  if (length(som_all$id_hs) > 0) {
    kable(som_all$muts_tab, format = "latex", caption = "Alle identifizierten somatischen Mutationen geordnet nach VAF.", booktabs = T, longtable = T, digits = 2, row.names = F, escape = FALSE) %>% kable_styling(latex_options = c( "HOLD_position", "repeat_header"), font_size = 9) %>% column_spec(c(8), width = "6em") %>% column_spec(c(2), width = "10em") %>% column_spec(c(1, 5), width = "4em") %>% column_spec(c(3:4), width = "4em") %>% column_spec(c(6, 9), width = "2em") %>% row_spec(0, angle = 60) %>% row_spec(som_all$id_hs, bold = TRUE)
  } else {
      kable(som_all$muts_tab, format = "latex", caption = "Alle identifizierten somatischen Mutationen geordnet nach VAF.", booktabs = T, longtable = T, digits = 2, row.names = F, escape = FALSE) %>% kable_styling(latex_options = c( "HOLD_position", "repeat_header"), font_size = 9) %>% column_spec(c(8), width = "6em") %>% column_spec(c(2), width = "10em") %>% column_spec(c(1, 5), width = "4em") %>% column_spec(c(3:4), width = "4em") %>% column_spec(c(6, 9), width = "2em") %>% row_spec(0, angle = 60)
    }
}
@

\clearpage
\section{ACMG Klassen}\label{ACMG_class}

\begin{itemize}
  \item \textbf{Kategorie 5}: Pathogen (pathogenic)
  \item \textbf{Kategorie 4}: Wahrscheinlich Pathogen (likely pathogenic)
  \item \textbf{Kategorie 4*}: Widersprüchliche Interpretationen der Pathogenität (Conflicting Interpretations of Pathogenicity)
  \item \textbf{Kategorie 3}: Unbekannte Signifikanz (uncertain significance)
  \item \textbf{Kategorie 2}: Wahrscheinlich Gutartig (likely benign)
  \item \textbf{Kategorie 1}: Gutartig (benign)
\end{itemize}

\clearpage
\section{Abkürzungsverzeichnis}

\begin{acronym}[PI3K-AKT-mTOR]
  \acro{VAF}[VAF]{Variant Allele Frequency}
  \acro{MAF}[MAF]{Minor Allele Frequency / Population Frequency}
  \acro{SNV}[SNV]{Single Nucleotide Variation}
  \acro{DNV}[DNV]{Dinucleotide Variation}
  \acro{InDel}[InDel]{Insertion and Deletion}
  \acroplural{InDels}[InDels]{Insertions and Deletions}
  \acro{CNV}[CNV]{Copy Number Variation}
  \acro{LoH}[LoH]{Loss of Heterozygosity}
  \acro{HS}[HS]{Cancer Hotspot Mutation}
  \acro{TSG}[TSG]{Tumorsuppressor Gene}
  \acro{OG}[OG]{Oncogene}
  
  \acro{REVEL-D}[D]{Deleterious}
  \acro{REVEL-N}[N]{Neutral}
  
  \acro{VarSome}[VarSome]{VarSome - The Human Genomic Variant Search Engine}
  \acro{VICC}[VICC MetaKB]{The Variant Interpretation for Cancer Consortium Meta Knowledgebase}
  \acro{InterVar}[InterVar]{Clinical Interpretation of genetic variants by ACMG/AMP 2015 guideline}
  \acro{ClinVar}[ClinVar]{Clinically Relevant Sequence Variations}

  \acro{nsSNV}[nsSNV]{nonysnonymous SNV / missense mutation}
  \acro{SG}[SG]{stopgain / nonsene mutation}
  \acro{SL}[SL]{startloss}
  \acro{nfsDel}[nfsDel]{nonframeshift deletion / in-frame deletion}
  \acro{nfsSub}[nfsSub]{nonframeshift substitution / missense mutation}
  \acro{fsDel}[fsDel]{frameshift deletion}
  \acro{nfsIns}[nfsIns]{nonframeshift inserstion / in-frame instertion}
  \acro{nfIns}[nfIns]{frameshift insterstion}
  \acro{splice}[splice]{splice region variant}
  
  \acro{RAF-MEK-ERK}[RAF-MEK-ERK]{RAF-MEK-ERK Signalweg}
  \acro{PI3K-AKT-mTOR}[PI3K-AKT-mTOR]{PI3K-AKT-mTOR Signalweg}
  \acro{DamResp}[DNA DamResp]{DNA Damage Response Signalweg}
  \acro{CellCycle}[Cell Cycle]{Zellzyklus}
  \acro{TyrKin}[TyrKin]{Tyrosinkinasen}
  
  \acro{BQSR}[BQSR]{Base Quality Score Recalibration}
\end{acronym}
\clearpage

\section{Informationen zu verwendeter Software und Paketen}

\subsection{Genom}
\begin{itemize}
\item UCSC hg19
\end{itemize}

\subsection{Programmversionen}
\begin{itemize}
\item FastQC: 0.11.10.devel
\item Trimmomatic: 0.39
\item bwa-mem2: 2.2.1
\item bam-readcount: 0.8.0-unstable-7-625eea2
\item samtools 1.10
\item GATK: 3.8-1-0-gf15c1c3ef
\item picard-tools: 2.20.6
\item VarScan: 2.4.4
\item annovar: 2020Jun08
\item bedtools: 2.28.0
\item Control-FREEC: 11.6
\item Java: openjdk-8-hotspot
\end{itemize}

\subsection{Annovar Datenbanken}
\begin{itemize}
\item refGene GRCh37
\item dbnsfp41a
\item avsnp150 (dbSNP)
\item clinvar\_20210223
\item intervar\_20180118
\item cosmic91
\item gnomad\_genome Version 2.1.1
\end{itemize}

\end{document}
